### ISSUE TITLE
decapitalization on tokens with added spaces

### ISSUE THREAD

**Issue by bmccann** [jekbradbury/revtok#1]
I expected `revtok.tokenize('Hello', decap=True)` to produce [' CAP ', 'hello '] or something similar, but it instead yields `[' Hello ']`.

**Comment by bmccann** [comment]
At first glance, it seems like removing  the condition executed at https://github.com/jekbradbury/revtok/blob/105750d71157a7e261762f193fe632da1565f0c5/revtok/tokenizer.py#L49 would give the behavior that I expect since this currently executes on all tokens that have a half space preceding the actual text.

**Comment by jekbradbury** [comment]
https://github.com/jekbradbury/revtok/commit/f74500ee2e7bf2f309ea9200c2f0955971496240
